name: "Build Preview Pages"

# プレビュー用ページをビルドする。
# 詳細： https://github.com/voicevox/preview-pages?tab=readme-ov-file#%E4%BB%95%E7%B5%84%E3%81%BF

on:
  push:
    branches:
      - main
      - project-*
  pull_request:

jobs:
  # このJobの名前を変更したときは、voicevox/preview-pages側のscripts/collect.tsも変更すること。
  build_preview_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Determine base
        uses: actions/github-script@v4
        id: determine_base
        with:
          script: |
            // Vitepressはbaseを相対パスにできない（https://github.com/vuejs/vitepress/issues/3057）ため、
            // ここでbaseを決定する。
            // ブランチの時は/preview-pages/preview/docs/branch-:name、
            // PRの時は/preview-pages/preview/docs/pr-:numberにビルドする。
            const branch = github.context.payload.pull_request?.head.ref || github.context.ref.replace('refs/heads/', '');
            const number = github.context.payload.pull_request?.number || '';
            const targetPath = number ? `pr-${number}` : `branch-${branch}`;
            core.setOutput('base', `/preview-pages/preview/docs/${targetPath}/`);

      - name: Build
        run: |
          pnpm run build --base ${{ steps.determine_base.outputs.base }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-pages
          path: "./src/.vitepress/dist"
